# Generated by Django 4.2.11 on 2025-03-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('CI', "Côte d'Ivoire"), ('GW', 'Guinée-Bissau'), ('ML', 'Mali'), ('NE', 'Niger'), ('SN', 'Sénégal'), ('TG', 'Togo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_titre', models.CharField(choices=[('BAT', 'BAT'), ('OAT', 'OAT')], max_length=3)),
                ('isin', models.CharField(max_length=12, unique=True)),
                ('denomination', models.CharField(max_length=200)),
                ('adjudication', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('date_valeur', models.DateField()),
                ('valeur_nominale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_coupon_couru', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_amortissement', models.CharField(choices=[('IN FINE', 'In fine'), ('LINEAIRE', 'Linéaire'), ('DIFFERE', 'Differe')], default='INFINE', max_length=10)),
                ('annees_differe', models.PositiveIntegerField(default=0)),
                ('prix_pondere', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='mon_app.pays')),
            ],
        ),
    ]
